spring:
  #  datasource:
  #    url: jdbc:postgresql://localhost:5432/donation_platform
  #    username: admin
  #    password: password
  jpa:
    show-sql: true

cors:
  allowed-origins: "http://localhost:5173"
