spring:
  application:
    name: backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

server:
  port: ${PORT:8080}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGIN}

jwt:
  secretKey: ${JWT_SECRET_KEY}
  expiration: 3600000 #1 година
  refreshExpiration: 2592000000 #30 днів

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

liqpay:
  public-key: ${LIQPAY_PUBLIC_KEY}
  private-key: ${LIQPAY_PRIVATE_KEY}
  server-url: ${SERVER_URL}
